### ISSUE TITLE
Add repology badge for "ocaml" package

### ISSUE THREAD

**Issue by XVilka** [ocaml/v2.ocaml.org#1015]
See the latest available version https://repology.org/metapackage/ocaml/versions
Usually it pushes distributions maintainers to keep the package more updated.
Adding a badge like this:
[![Packaging status](https://repology.org/badge/vertical-allrepos/ocaml.svg)](https://repology.org/metapackage/ocaml)

And everyone can see who is being slow on updating the package.

**Comment by Chris00** [comment]
> And everyone can see who is being slow on updating the package.

The purpose of the website is not to assign blame to who is slow to update packages. :-)

**Comment by XVilka** [comment]
Of course is not. But surely it will help wider adoption of nicer things from the latest versions of OCaml.

**Comment by pmetzger** [comment]
I agree this would be great to do. That said, @XVilka, can you do a pull request for this rather than an issue? I'd suggest it _not_ be on the front page, probably on one of the getting OCaml pages. (BTW, @Chris00, note that I'm one of the red lines in that list, I maintain MacPorts, and I don't mind this.)

**Comment by XVilka** [comment]
Will do.

**Comment by XVilka** [comment]
https://github.com/ocaml/ocaml.org/pull/1018

**Comment by pmetzger** [comment]
Cool, I've commented there.

**Comment by Chris00** [comment]
Thanks for the PR and the review.

**Comment by pmetzger** [comment]
BTW, how long until this appears on the web site itself?
