### ISSUE TITLE
make separate pages for Consortium and OCaml Labs

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#110]
These are currently inlined in [Support](http://ocaml.org/support.html), and are not particularly prominent. It's hard to see the distinction between the Consortium and OCaml Labs sections. This is perhaps just a styling issue, but it might be better to make the Support page analogous to the proposed Groups page. Just be a list of organizations with short descriptions and links to the organizations' main pages.

Then, we can move the content of the Consortium section to consortium/index.html. For OCaml Labs, I'm not sure. We could make an ocamllabs/index.html page, or maybe we should simply link to the OCaml Labs website. Otherwise, we'll start duplicating content.

**Comment by avsm** [comment]
we're going to do another round of improving the OCL web pages, so happy to start moving stuff onto OCaml.org as appropriate /cc @amirmc

**Comment by amirmc** [comment]
This is already on my list. As part of the design stuff, I'm looking at two related things (1) content across the site and (2) wireframes for layout. 

Wherever possible, I'm trying to include some content in the wireframes (rather than 'lipsum') so it's clearer what I'm aiming for. @agarwal can see them and I want to do mockups for the 4 heading pages before I ask for feedback. 

I should make a new issue about this with details (will do so when later tonight). 

Best wishes,
Amir

## 

sent via mobile

**Comment by amirmc** [comment]
Relevant to #113

**Comment by agarwal** [comment]
Closed by 45c83647726705b6dbd7991959ade89110d8ee79.
