### ISSUE TITLE
404 on logos

### ISSUE THREAD

**Issue by pw374** [ocaml/v2.ocaml.org#1229]
404 on logos from https://ocaml.org/docs/logos.html

**Comment by patricoferris** [comment]
Thanks for the report :)) After a lot of Github archaeology I think I've found the source of this bug -- it seems the logos have always been vendored in manually (it's never been part of the build script). The logos coming from https://github.com/ocaml/ocaml-logo.

 - From 2014: https://github.com/ocaml/ocaml-logo/issues/2#issuecomment-39951892 
 - From 2016: https://github.com/ocaml/ocaml.org/issues/850#issuecomment-259033523
 
I guess the solution is either to make that part of the build script or for the OCurrent deployer to do it  i.e. modify the Dockerfiles to have a: 

```dockerfile
RUN git clone https://github.com/ocaml/ocaml-logo /home/opam/src/ocaml.org/logo
```

The dockerfile approach might be best because the links are protocol relative (e.g `//ocaml.org/logo/Colour/PNG/colour-logo.png`) so even if the build script added the ocaml-logo repo, people developing locally using something like `cohttp-server-lwt` wouldn't see the logos anyway. 

cc: @avsm

**Comment by patricoferris** [comment]
The logos should be fixed :)) https://ocaml.org/docs/logos.html

**Comment by avsm** [comment]
Confirmed fixed. Thanks @patricoferris for the PR in #1230!
