### ISSUE TITLE
Git log of contributors is empty

### ISSUE THREAD

**Issue by patricoferris** [ocaml/v2.ocaml.org#1247]
Currently, the site has a [contributors page](https://ocaml.org/contributors.html) and as part of that page there should be a list of authors extracted for them git log, but as you can see from the screen-shot 

![Screenshot 2021-03-03 at 11 56 59](https://user-images.githubusercontent.com/20166594/109802340-96248580-7c17-11eb-8b24-6cf847d7bb0f.png)

that list on the production site is currently empty. However, when developing locally at least on my machine (`make production`) and serving the site from the `ocaml.org` directory the git log is there. This makes me think there could be an issue in the Dockerfile used for deploying the site, so to tackle this issue you may need to try building the docker-ized site locally (`docker build . --file=Dockerfile.deploy -t ocamlorg-deploy`) and having a look at how we deploy the site using [OCurrent](https://deploy.ocamllabs.io/?repo=ocaml/ocaml.org).

**Comment by patricoferris** [comment]
@IIITM-Jay would you be interested in looking at this?

**Comment by IIITM-Jay** [comment]
@patricoferris Thank you so much for pinging me here. I am going through what you have suggested and asked above and will let you know soon.

**Comment by IIITM-Jay** [comment]
@patricoferris why we are using opam-repository, in the following lines below :point_down: 

```RUN git -C /home/opam/opam-repository pull origin master && git -C /home/opam/opam-repository checkout c1952fb63c5a89c8c4230aac0360884518d72d91 && opam update -u -y```

can't we use the latest commit present in this repository itself like the way to build the site given in OCurrent deployer while building ```live_www_ocaml_org```

**Comment by patricoferris** [comment]
Good question. 

The main reason, as far as I know, for this command is reproducibility and stability. The OCaml.org site doesn't have too many dependencies and certainly doesn't add or change dependencies very often. With this command, if the deployment fails, it's much easier to reproduce the exact environment locally to test it rather than trying to work out which commit of opam-repository was used. 

> like the way to build the site given OCurrent while building live_www_ocaml_org

I don't quite follow what you mean by this, the live deployment of the site does reset the opam-repository commit if I'm not mistaken. See:  https://deploy.ocamllabs.io/job/2021-02-26/175930-ocluster-build-c20284

**Comment by IIITM-Jay** [comment]
> The main reason, as far as I know, for this command is reproducibility and stability. The OCaml.org site doesn't have too many dependencies and certainly doesn't add or change dependencies very often. With this command, if the deployment fails, it's much easier to reproduce the exact environment locally to test it rather than trying to work out which commit of opam-repository was used.

Got crystal clear of the points you mentioned above.
@patricoferris I have few questions and suggestions as well regarding this issue. When I was going through the ```contributors.md``` file, I found the below  mentioned command for displaying the contributor's list :point_down: 

```((! cmd git log --format="%aN" | sort -k 2 | uniq | sed -e "/^[^ ]*$/ d" -e "s|\(.*\)|<li>\1</li>|" !))```

Some of the few points regarding the above linux command which I would like to discuss here:
1. First and the foremost drawback using this command is that it looks so complicated, that it can't be understood to the new users of Linux command or the window users, though I know the usage of ```sed``` and ```awk```, but I usually prefer ```awk``` command to display efficiently.

2. This command does not give the desired output which is actually wanted. The reason is that the ```sort``` is not sorting out in alphabetical order.

3. The overall command is not an optimized one and not flexible too due to the regular expression used  to formulate ```sed -e "/^[^ ]*$/ d" -e "s|\(.*\)|<li>\1</li>|" !))```

Few of my **suggestions**:
1. The correct command to get alphabetically sorted list (which I must guess the desired one) is as follows: 
```((! cmd git log --format="%aN" | sort | uniq | sed -e "/^[^ ]*$/ d" -e "s|\(.*\)|<li>\1</li>|" !))```
***(Note: the difference in ```sort``` command)*** 

2. The optimized one and the most flexible way of doing the same as above is via using ```awk``` which is quite understandable and meaningful too:
 ```git log --format="%aN" | sort | uniq | awk '{print "<li>"$1,$2,$3"</li>"}' ```

     in above it's simply printing the fields 1,2 & 3, which contains full names of the contributors.

3. We can also use ```git shortlog -s``` in order to sort the contributors by the number of their respectful commits.

What do you say @patricoferris ? :thinking: 
What's your opinion regarding above...

**Comment by pw374** [comment]
how about `sort -u ` instead of `sort | uniq`?

**Comment by IIITM-Jay** [comment]
> how about `sort -u ` instead of `sort | uniq`?

That's really got skipped... absouletly ```sort -u``` is the merging of the two ```sort``` and ```uniq``` and behaves identically i.e. ```sort -u``` and ```sort | uniq```

**Comment by IIITM-Jay** [comment]
@pw374 I have done a PR  #1253 for the above-discussed points. But the build failed :disappointed: . I am not getting the appropriate reason for this. Have I done something wrong ... or missing something. May I request any help...  :pray:

**Comment by IIITM-Jay** [comment]
My bad :disappointed_relieved: , finally caught the mistake of a single quote which I was missing earlier...
Now working perfectly..
Thank you once again :pray:

**Comment by IIITM-Jay** [comment]
Hi @patricoferris what's your opinion ... waiting for your feedback and valuable suggestions...
Thank you.

**Comment by avsm** [comment]
Fixed in #1253
