### ISSUE TITLE
Images on opam.ocaml.org don't have alt text

### ISSUE THREAD

**Issue by gs0510** [ocaml/v2.ocaml.org#1328]
The Github, OCamlPro and Ocaml icons in the footer of `opam.ocaml.org` do not have alt text which might be helpful to screen readers.

You can add an alt text to the image like so:
```
<img src="/ext/img/favicon.png" alt="Image description">
```

**Comment by somya104** [comment]
Hey @patricoferris and @gs0510
I am Somya Srivastava.
I am an outreachy applicant and would like to work on this issue.

**Comment by Lovelyfin00** [comment]
Hi @patricoferris @gs0510 
I'm Loveth and an outreachy applicant. I would love to work on this issue.
Thanks

**Comment by gs0510** [comment]
@somya104 Please go ahead, you can work on this issue. :)

**Comment by somya104** [comment]
Hey @gs0510 ! Due to Covid situations at home, I will be giving an update in 3-4 days. 
Sorry for being late.

**Comment by gs0510** [comment]
Okay, no worries. Please take your time @somya104

**Comment by somya104** [comment]
Hey @gs0510 ! I have gone through all the files in the ocaml.org repository. However, I'm unable to find the code for footer for opam.ocaml.org; I have found the code for the main web page of the opam.ocaml.org website but that code did not contain the footer code that I need. I have also viewed a file named Superfooter in which only this code is available:
```
<div class="footer">
<t:insert xmlns:t="http://ocaml.org/xmlns/template#" name="footer"/>
</div>
```
As far as my understanding, I went to the template folder to check the footer file and couldn't find the the desired code there too.
I then went to the website through Google Chrome, right clicked and viewed the page source so that it becomes easier for me to search the code through VSCode but couldn't locate it.
I have build the system locally by following all the steps given on CONTRIBUTING.md and have also ran make which successfully worked.
Am I missing a step or something or is the code located in a different repository?
Please help me out.

**Comment by gs0510** [comment]
Hi @somya104! The code for opam.ocaml.org does reside in another repository and turns out is out of scope for now. My apologies, you can work on another issue in the meantime :)

**Comment by patricoferris** [comment]
Closing for now

**Comment by somya104** [comment]
Hey! @patricoferris and @gs0510 
I am still learning OCaml and I figured that opam.ocaml.org has been written in the same language instead of HTML. Hence, I tried something though there might be a syntax error.
Can you please take a look at the issue I have linked above and review it?
Thanks!
