### ISSUE TITLE
Table of Content in News section not arranged properly

### ISSUE THREAD

**Issue by Lovelyfin00** [ocaml/v2.ocaml.org#1390]
One of the list in the table of content isn't arranged properly. I would love to fix this issue if it gets approved.

![First issue](https://user-images.githubusercontent.com/38161296/113479741-a59e2500-9488-11eb-849f-c44a4f6b230a.png)

**Comment by patricoferris** [comment]
Hi @Lovelyfin00, 

Thank you for taking the time to open this issue. IIRC, the `news` page is generated by reading RSS feeds of all the "`syndications`" and we (the ocaml.org site) simply present whatever gets returned to us. If you follow the link to Thomas Leonard's (very good!) blog post you will see this is actually part of their table of contents so the indentation is indeed correct. 

Again, thanks for checking this and opening the issue. I'm going to close it now because it isn't a bug.
