### ISSUE TITLE
site display could be improved on a small screen view 

### ISSUE THREAD

**Issue by yashi-hub** [ocaml/v2.ocaml.org#1414]
when navigating to the site -https://www.infoq.com/presentations/ocaml-browser-iot/?utm_source=twitter&utm_medium=link&utm_campaign=qcon , the top bar shows various options such as streaming, Machine learning, etc. 
this gets hidden when used on a small screen. and instead, users have to scroll right which is a bit inconvenient.

large screen -
![error initial](https://user-images.githubusercontent.com/69522036/113569781-abcf0580-9630-11eb-8986-6bb89940ada8.png)

mobile screen or a screen smaller -
![error final](https://user-images.githubusercontent.com/69522036/113569801-b8535e00-9630-11eb-8be5-09de36651960.png)

instead, a new div that contains the hidden elements can be added below the already present one , just when they start getting hidden as the screen size decreases. This makes the site more resonsive.
 
if this issue gets approved , I would love to work on this :))

**Comment by patricoferris** [comment]
Hi @yashi-hub 👋 

I agree this UI is a bit strange but I don't think there's anything we can do about it because it's the infoq website? Am I missing something here?

**Comment by yashi-hub** [comment]
@patricoferris this UI can be changed but one thing that confuses me is 
![smaller screen view](https://user-images.githubusercontent.com/69522036/113853030-d3ea7000-97ba-11eb-9817-5c183540d200.png)
where do I find this code repo?
the standard ocaml.org repo with which all the code is related doesn't have any folders like shown in the dev tools sources.
is it possible that we can access this code with the help of some repo? or is it confidential?

**Comment by Ndipbanyan** [comment]
> Hi @yashi-hub 👋
> 
> I agree this UI is a bit strange but I don't think there's anything we can do about it because it's the infoq website? Am I missing something here?

@yashi-hub I think what  @patricoferris is trying to highlight here is  that you probably can't do anything about this because it is the infoq website and not the ocaml website and just as you mentioned in your comment earlier and I quote "the standard ocaml.org repo with which all the code is related doesn't have any folders like shown in the dev tools sources", this issue isn't within the ` Improving ocaml.org website` scope. I hope this comment makes it clearer for you. This is just me trying to help, except if there is something else I am missing that @patricoferris might need shed some light on.  Thanks

**Comment by yashi-hub** [comment]
@Ndipbanyan I get your point and also understood where I was wrong. thankyou so much for helping me out :)) 
@patricoferris should I close this issue now?

**Comment by patricoferris** [comment]
No worries I can close it -- thanks for clarifying @Ndipbanyan :))
