### ISSUE TITLE
Adding dropdown menu for site translation to enhance accessibility 

### ISSUE THREAD

**Issue by Riddhima23** [ocaml/v2.ocaml.org#1427]
The current list to translate could be a bit confusing with many people not knowing short forms of various languages. Also the current format would look messy when other languages are added hence I would like to create a dropdown menu somewhat like this:
<img width="375" alt="Screenshot 2021-04-06 115243" src="https://user-images.githubusercontent.com/58878761/113667956-29e1e980-96cf-11eb-853f-594e38757bad.png">
 I would like to work on it once approved :)

**Comment by pitag-ha** [comment]
There is already someone working on improving the language selector layout. See [here](https://github.com/ocaml/ocaml.org/issues/1378#issuecomment-814478663) :)

**Comment by Riddhima23** [comment]
@pitag-ha wouldn't the [proposed layout](https://github.com/ocaml/ocaml.org/issues/1378#issuecomment-814478663) still look messy if more languages are added!? I wanted to implement a dropdown menu to select language which will look clean and comapact even when we have number of different languages. Just a suggestion.Please correct me if I am wrong :)

**Comment by pitag-ha** [comment]
Yes, a dropdown has advantages :) I wanted to point out that someone was already working on the language selector layout, since I'd like to avoid that applicants step on each other's toes. Now it's even worse: there is already a [PR](https://github.com/ocaml/ocaml.org/pull/1466) implementing exactly the idea of this issue (and another [PR](https://github.com/ocaml/ocaml.org/pull/1464) implementing the other idea). I'm really sorry! I hope you haven't started working on this.

**Comment by Riddhima23** [comment]
@pitag-ha no no I haven't started yet. I get what you are saying ,you are right. Nevermind I'll find something else. Thank you :)
