### ISSUE TITLE
[OCaml99] Bug: #21 Insert an element at a given position into a list.

### ISSUE THREAD

**Issue by jianingy** [ocaml/v2.ocaml.org#145]
```
let rec insert_at x n = function
    | [] -> []
    | h :: t as l -> if n = 0 then x :: l else h :: insert_at x (n-1) t;;

insert_at `alfa 0 [] ;;
val insert_at : 'a -> int -> 'a list -> 'a list = <fun>
#   - : [> `alfa ] list = []
```

This solution returns an empty list when its input is an empty one. However, I suppose it would make sense if it returns "[`alfa]". So the solution might be 

```
let rec insert_at x n = function
    | [] -> [x]
    | h :: t as l -> if n = 0 then x :: l else h :: insert_at x (n-1) t;;

insert_at `alfa 0 [] ;;
val insert_at : 'a -> int -> 'a list -> 'a list = <fun>
#   - : [> `alfa ] list = [`alfa]
```

What do you think?

**Comment by agarwal** [comment]
Thanks for pointing this out. The issue is more general. You might not like this answer either:

```
insert_at `alfa 1 [`a];;
- : [> `a | `alfa ] list = [`a]
```

The problem specification is incomplete. It doesn't specify what should be done when `n` is outside the range of the given list. One possibility is to add the following to the requirements:

> If `n` is outside the range of the given list, then return the list unaltered.

Then, I think the current solution is valid. Or we might think giving `n = 0` or `n = m + 1`, where `m` is the list length minus 1, should be acceptable. In this case, the current solution is incorrect.

**Comment by jianingy** [comment]
Alright. That's no problem if the requirements say so. :)

**Comment by agarwal** [comment]
Re-opening this issue since neither the proposed change to the solution or the documentation have been implemented.
