### ISSUE TITLE
Fix the ordering of blogs

### ISSUE THREAD

**Issue by pitag-ha** [ocaml/v2.ocaml.org#1534]
There is a [FIXME](https://github.com/ocaml/ocaml.org/blob/master/script/rss2html.ml#L191) in the code ordering blogs by name concerning the following: a leading white space in the name of a blog will impact the ordering. So ideally leading white spaces should be removed before ordering, but arent' at the moment. I propose fixing that.

**Comment by shreyaswikriti** [comment]
I would like to work on this.

**Comment by pitag-ha** [comment]
Sure @shreyaswikriti, go ahead :)

**Comment by mercybassey** [comment]
This issue looks interesting. I guess its already assigned. I'm currently looking for a medium issue @pitag-ha

**Comment by Lontchi12** [comment]
@pitag-ha  i would really like to work on a medium issue but i can't find please can you help?

**Comment by shreyaswikriti** [comment]
Hii @pitag-ha, what I learnt from this issue is I have to remove leading whitespace before ordering blogs. I am thinking to do string.trim on the name strings. before sorting. (for example) I made a list of strings having leading spaces etc. After that, I run this function (just experimenting)
_**let trim str = String.trim str in  
let by_name o1 o2 = String.compare (trim o1) (trim o2) in 
  List.sort by_name ["  hello "; "abc"; "amisha "; " ght"; "shreya"; "ghthhh"];;**_
**OUTPUT (I am getting)**
_**- : string list = ["abc"; "amisha "; " ght"; "ghthhh"; "  hello "; "shreya"]**_
I don't know why the sorted list again with white spaces.

 **_#let c a b  = String.compare a b ;;
val c : String.t -> String.t -> int = <fun>
#c " hello" "hello" ;;_** 
- : int = -1 //showing first string > second string
**_#by_name " hello" "hello" ;;_**
- : int = 0 // showing both are equal

 Am I going in the wrong direction? Kindly guide. Thanks.

**Comment by shreyaswikriti** [comment]
@pitag-ha, kindly review the PR.

**Comment by pitag-ha** [comment]
> I don't know why the sorted list again with white spaces.

That's because strings are immutable in OCaml :) What you do here is that inside the scope of `by_name` you create two new strings `trim o1` and `trim o2` from the strings `o1` and `o2`. Those new strings just serve to determine how to order `o1` with respect to `o2`. As you can see the ordering is done correctly with your change.

So your PR looks good :) Just apply the changes proposed by Gargi.
