### ISSUE TITLE
Community > Mailing lists: menu item points to external content

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#19]
Link currently goes to Inria page. This content should be imported directly into ocamlweb repo.

**Comment by eelsther** [comment]
Commit 1d0bbb2

**Comment by Chris00** [comment]
P.S. Since oasis is required to compile the project, I propose we use

  oasis setup -setup-update dynamic

and do not commit _tags,...  If we want oasis not to be needed, we have to commit more stuff or maybe periodically release some tarball containing the extra (setup.ml, _tags, myocamlbuild.ml,...) — this may be the easier to lower the barrier of entry, even though the other dependencies are still needed.
