### ISSUE TITLE
"install" vs "install on MacOSX"

### ISSUE THREAD

**Issue by zacchiro** [ocaml/v2.ocaml.org#201]
There are at least two "install" links on the current website preview.
- one under Learn, which on my (GNU/Linux) laptop reads "Install on MacOSX" and has sub-links "other systems" and "what's new?"
- another under Platform, which reads "Install"

I think we should have only one download button, ideally in a single place.

If it has to appear on multiple pages, then it should appear consistently, always with the same label and links.

Aside, I don't think we should recommend a specific platform (MacOSX in this case), especially if it is a non-free one. If we can autodetect the user system, fine, otherwise we should just point to a download page where _the user_ can choose her own platform.

TIA,

**Comment by amirmc** [comment]
The download button appears on three pages (front-page, learn and platform) and always points to the same location.  I agree that the button should be consistent across those pages so I've changed the wording on it and hidden the links ('other systems' and 'what's new')

The MacOSX reference was a left-over item from the design-stage, as we wanted to have browser detection and point the link directly to the appropriate section of the install page.  Since we don't (yet) have that, it shouldn't have found it's way through to the preview.  Thanks for pointing it out!
