### ISSUE TITLE
Use relative links

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#219]
The fact that the CSS and images use global links make it difficult for a contributor to preview his changes on his machine (this was possible with the old site).  IMHO, relative links should be preferred.

**Comment by pw374** [comment]
That's a non-trivial refactoring issue. :-/

**Comment by Chris00** [comment]
Not really if you can define (automatically) a variable `path-to-root` and prefix your URLs with that.  

A related question is why the compiling logic is implemented in scripts (including for generating some page content).  Wouldn't it be easier to do it all in OCaml (avoiding altogether the shell, thus providing the additional benefit to compile on Windows).

**Comment by pw374** [comment]
> Not really if you can define (automatically) a variable path-to-root and prefix your URLs with that.

Yes and no: the yes part is obvious of course, the no part is that it makes it harder for people to contribute without forgetting to put that prefix.

> A related question is why the compiling logic is implemented in scripts (including for generating some page content). Wouldn't it be easier to do it all in OCaml (avoiding altogether the shell, thus providing the additional benefit to compile on Windows).

Well, the thing is, I'm betting that virtually any contributor can understand the makefile-based build system.
Doing everything in OCaml — in my opinion — makes it **very** difficult to contribute and to make components evolve, because doing so means understanding the whole build system. My love for the OCaml language will not make me believe that any OCaml-friendly people can really contribute to a website that's entirely built using OCaml solely. And that's because `ocaml.org` is a website that provides static contents and has potentially loads of contributors who have very different backgrounds. So it's the reason I believe we should prioritise the easiness of access over the potential elegance and uniformity provided by the use of OCaml solely.

I do agree that it's sad and bad that it doesn't build seamlessly on Windows, but I also believe we're excluding less people with this kind of constraints (i.e., requiring cygwin or something like that) than with the "let's do everything in OCaml" for this particular kind of website. (Please tell me if I'm wrong.)

**Comment by amirmc** [comment]
Regarding builds, we should also be able (eventually) to set up a system where nothing has to happen locally on a users' machine if they just want to see their changes (i.e just push changes to a fork and something get's built elsewhere).  Anil's work with Travis will be helpful when we get to that.

**Comment by Chris00** [comment]
On Fri, 8 Nov 2013 06:09:04 -0800, Philippe Wang wrote:

> |
> |
> 
> Not really if you can define (automatically) a variable path-to-roo 
> t and prefix your URLs with that.
> 
> Yes and no: the yes part is obvious of course, the no part is that  
> it makes it harder for people to contribute without forgetting to p 
> ut that prefix.

Right.  An alternative would be for a script to rewrite these links a 
s relative so the user does not have to care.

> I do agree that it's sad and bad that it doesn't build seamlessly o 
> n Windows, but I also believe we're excluding less people with this 
>  kind of constraints than with the "let's do everything in OCaml" f 
> or this particular kind of website. (Please tell me if I'm wrong.)

My idea was not to ditch make completely — make can be installed on W 
indows with little effort.  I was more thinking about the shell code  
that is used to fill some templates (e.g. tpl/front_news.mpp).  Maybe 
 that could be advantageously replaced by a plugin system for MPP??

**Comment by Chris00** [comment]
A `preview` target has been added by commit 9c031ce23b19124c4bf0a7e1d841d29c9de141d5 which transform all local absolute links to relative ones.
