### ISSUE TITLE
Point of src/?

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#227]
Is there a point in having the `src/` directory?  We could just move everything up, move the programs to `app/` and maybe tweak _oasis to compile them.

**Comment by agarwal** [comment]
I like to have the src/ directory but appreciate that many people think
it's unnecessary. My reason for having it is that it clearly indicates
where all raw source code (and content in the case of this repo) go. I
sometimes have a bin/ directory, which contains build scripts, maybe an
etc/ directory containing other data, and so on. I'm happy to flatten the
structure if others prefer.

**Comment by Chris00** [comment]
In principle I agree.  However, in this case, the `Makefile`, `README.md`,... are already in `src/`, nothing in `src/..` is needed for the final site — and will eventually be removed.  Hence my question (if we keep `src/`, I think the final site should be built in `src/..` and not in `src/` and build scripts should move one level up).

**Comment by agarwal** [comment]
Yes, I think all the build scripts should be moved one level up. We still have the old scripts in root, which should be deleted.

**Comment by pw374** [comment]
Well, I guess that we could simply have the current src as /, and perhaps src/site as src.

**Comment by amirmc** [comment]
I agree that all of the old/unused material should be removed.  It's confusing if you're new to the repo, especially since they're at the root level.

I'm fine with flattening the structure if others agree as it does make it clearer where the content for the site lives.  I also think that the final output folder (`ocaml.org`) should be made on the root, rather than in `src`.

**Comment by pw374** [comment]
The person who moves those files should also adapt the building script on preview.ocaml.org, else it'll break.

(and maybe [tpl/main.mpp](https://github.com/ocaml/ocaml.org/blob/redesign/src/tpl/main.mpp) as well)

**Comment by agarwal** [comment]
I think `src/lib` and `src/app` can also be deleted, right? So really we just have `site` and `tpl` sub-directories. I think we can just move them up one level. I wouldn't rename `site` to `src` because `tpl` is also source code, so that would be confusing. The name `site` is intuitive, so I would leave that name. Should we rename `tpl` to `templates`? It's really not obvious what `tpl` means. I keep wanting to read it as _tuple_.

**Comment by amirmc** [comment]
> "It's really not obvious what `tpl` means. I keep wanting to read it as _tuple_."

lol, I do the same.  Yes, I think we should rename it to be clearer and `templates` sounds fine to me.

Do we have a consensus on what to do about the structure? If so, we should decide who'll make the changes so that we can avoid messy merge conflicts.

**Comment by Chris00** [comment]
No, `src/app` is used by the current scripts.  Actually, I think the scripts should move in there (and be compiled or have a symlink to the executable in the base dir).  For the moment `src/lib` is useless but maybe we want to put a plugin for the `ocamldoc` later in there.

**Comment by agarwal** [comment]
Okay, so we keep `app` too, and maybe later add `lib` again. I still think it would be okay to move all directories up one level if that's what you all want. I can make the change but it won't be for a few hours.

**Comment by Chris00** [comment]
Fine with me.
One can wonder whether one want to enable compilation through `_oasis` but that can be done later.

**Comment by pw374** [comment]
> I can make the change but it won't be for a few hours.

I've just adapted `/home/buildpreview/build_ocaml.org.bash` so that if the contents of `src` is moved one level up, it'll still work.

**Comment by agarwal** [comment]
I'm working on this issue now.

**Comment by Chris00** [comment]
Great.

**Comment by agarwal** [comment]
I've just pushed a new `cleanup` branch. It compiles for me, but I'd appreciate if others can quickly try and let me know if it works for you.

I still want to move scripts all under the script/ directory.

**Comment by amirmc** [comment]
Works for me.  I'm wondering how many of the other files we can move out of root.

**Comment by agarwal** [comment]
I've moved all script files out of root. One final simplification might be to merge the 4 Makefiles into 1. Let's open a separate issue for that as I'd like to merge the current work into `redesign`, so that other issues don't get blocked.

**Comment by Chris00** [comment]
On Mon, 11 Nov 2013 15:43:43 -0800, Ashish Agarwal wrote:

> I've moved all script files out of root. One final simplification might be to
> merge the 4 Makefiles into 1. Let's open a separate issue for that as I'd like
> to merge the current work into redesign, so that other issues don't get
> blocked.

I am doing it.  Please wait for 1 min.

**Comment by Chris00** [comment]
On Mon, 11 Nov 2013 15:43:43 -0800, Ashish Agarwal wrote:

> I've moved all script files out of root. One final simplification might be to merge the 4 Makefiles into 1. Let's open a separate issue for that as I'd like to merge the current work into redesign, so that other issues don't get blocked.

I am not sure it is a simplification.  The separation makes it easier to track what is needed to compile web pages.  If anything, I would move Makefile.from_html and Makefile.from_md to scripts because that is how they ought to be considered.

**Comment by agarwal** [comment]
Philippe may want to comment also. Is it okay if we just open a separate issue, and I can merge `cleanup` into `redesign`.

**Comment by Chris00** [comment]
Yep.

**Comment by pw374** [comment]
The purposes of those 4 makefiles are:
- Makefile.from_html and Makefile.from_md: 2 makefiles that contain rules that would be in conflict if in the same makefile.
- Makefile.common: put the rules that are common to generating HTML from HTML and generating HTML from MD.
- Makefile: give a default entry point. It could just be Makefile.common instead, but having a separate file for Makefile.common says "there are things in common for 2 ways to generate HTML". The argument for Makefile and Makefile.common being 2 files instead of just 1 is that it's easier to see that the rules in Makefile.common are used by different makefiles. If Makefile.common is renamed Makefile, then one doesn't see from the name of the file that it's included by several makefiles.

If you have a better idea, I don't mind changing that.

**Comment by agarwal** [comment]
What parts of Makefile.common are really needed in Makefile.from_{md,html}? Ideally, Makefile would have commands that you mostly need, and the other files would be hidden under script/. We can't do that right now because Makefile has no content, so it wouldn't serve its purpose of letting us know what the main commands are.

**Comment by pw374** [comment]
The problem if you have script/Makefile.from_{md,html} instead of Makefile.from_{md,html} is that to build an HTML from a Markdown file, you'd have to run `make -f script/Makefile.from_md somepage.md` instead of `make -f Makefile.from_md somepage.md`  and that's bothering me. However, if you really want to move them to `script/` then I guess ["I would move Makefile.from_html and Makefile.from_md to scripts"](https://github.com/ocaml/ocaml.org/issues/227#issuecomment-28257981) becomes fully relevant. But then we would rely on `make` anymore but on a script. I'm not strongly against it, but I do prefer using `make` wherever it's relevant for uniformity... My only strong opinion about the build system is that it should be easy to understand for any programmer (including those who have never ever used oasis, ocamlbuild, or not-so-well-known tools like that), otherwise it'll scare away potential contributors.

**Comment by Chris00** [comment]
Can we delete the `cleanup` branch?

**Comment by agarwal** [comment]
> Can we delete the cleanup branch?

I already did.

**Comment by agarwal** [comment]
I agree having to write "script/foo" is more annoying than "foo". However,
the tradeoff is we currently have 4 makefiles very prominently visible,
which causes information overload. Most of the time, most contributors just
need to know about "make" and "make preview". Everything else is a detail
and it's cleaner to avoid having all the other information so visible.

**Comment by pw374** [comment]
Should we close this issue?

**Comment by pw374** [comment]
Actually, let's close this issue, since it's titled "Point of src/?" and there's no `src/` anymore.
