### ISSUE TITLE
enable testing with Travis

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#241]
Comments in a few other issues have mentioned that we should build the site with Travis. I'm opening this issue, so we don't forget. See Anil's [post](http://anil.recoil.org/2013/09/30/travis-and-ocaml.html) about using Travis for OCaml projects.

**Comment by amirmc** [comment]
Specific refs for context:
- https://github.com/ocaml/ocaml.org/issues/230#issuecomment-28177599
- https://github.com/ocaml/ocaml.org/issues/219#issuecomment-28066316
- https://github.com/ocaml/ocaml.org/issues/238#issuecomment-28237703

**Comment by pw374** [comment]
I'm testing travis there https://travis-ci.org/pw374-travis/ocaml.org/

**Comment by pw374** [comment]
So, it currently takes between 3 and 5 minutes for travis to build the website from a fresh VM, using Anil's instructions. Most of the time is spent building the environment... 

Well, it's very nice. :)

**Comment by avsm** [comment]
Nice!

**Comment by pw374** [comment]
I'm not completely sure yet how to handle permissions for travis. I mean, it asked for a lot of permissions on my github account, so I created another github account. (@avsm you said it'd ask for twitter account authentication but I was asked for github account authentication, I don't know if you made a typo or if it's because of something else.)

Meanwhile, those 2 files could serve as a base when/if we install Travis on the main repo:
https://github.com/pw374-travis/ocaml.org/blob/redesign/.travis-ci.sh
https://github.com/pw374-travis/ocaml.org/blob/redesign/.travis.yml

**Comment by Chris00** [comment]
@agarwal @avsm Are the current build scripts OK or do we still desire to use Travis?

**Comment by agarwal** [comment]
In #532, we're requesting to improve the build scripts and in particular check them into the repo. This issue suggests enabling testing with Travis (but I see now the title is misleading). So we want both: we're not happy with the build scripts, and we do desire to use Travis. #532 is more important in my opinion, and likely a prerequisite for this issue.

**Comment by agarwal** [comment]
Uhhh... sorry. I'm not thinking. Issue #532 is about server side scripts, which is not necessary for enabling testing with Travis. By "build scripts", if you mean strictly building then I guess they are okay. I kind of thought of "build scripts" to mean "build and deploy scripts".

**Comment by Chris00** [comment]
@avsm Could you turn on Travis for ocamlorg?

It would be nice to push a preview for each PR on an URL `.../<git hash>/`.  These could be erased (some time) after the PR has been merged or when they are too old.  (We should try to avoid duplicating the images when they have not changed though.)  I do not think the Travis script should upload the generated content somewhere as it would be weak security-wise, except maybe on github-pages (but the whole generated site for all PRs being there forever is not really great...).  Or maybe a compilation on one of our machines (possibly in a container), using PR triggers — a la @Camelus?  Any thoughts?

**Comment by amirmc** [comment]
I've just turned on Travis for this repo [1] but it'll still need the relevant scripts in the repo in order to work.

Re: The staging comments. One of the thoughts we had some time ago was to build and preview the site for each PR exactly as you suggest. It should be served from one of our own machines so we could remove the older ones easily.  Part of this was thinking about using Mirage to build a (disposable) image for each PR (e.g. just the unix backend would be fine).

[1] https://travis-ci.org/ocaml/ocaml.org

**Comment by Chris00** [comment]
> I've just turned on Travis for this repo [1] but it'll still need the relevant scripts in the repo in order to work.

They [are](https://github.com/ocaml/ocaml.org/blob/master/.travis.yml) [present](https://github.com/ocaml/ocaml.org/blob/master/travis-ci.sh).  Please force a build.

**Comment by Chris00** [comment]
I have pushed a new commit — build started.

**Comment by amirmc** [comment]
Thanks. I'm not sure that the current scripts set up the environments appropriately.  Perhaps we want to use the scripts at: https://github.com/ocaml/ocaml-travisci-skeleton?

**Comment by Chris00** [comment]
It is because I enabled caching in order not to have to rebuild the compiler each time.  I think the last push made it work.
