### ISSUE TITLE
Download/Install page design feedback

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#256]
from @edwintorok at https://github.com/ocamllabs/sandbox-ocaml.org/issues/20

---

In general I like the landing page redesign, but there are some aspects that I liked better on the old site, the install page is one of them.

Clicking on "Download OCaml" should take me to http://ocaml-redesign.github.io/docs/install directly, instead of jumping through the platform. TBH I like the old http://ocaml.org/releases/ page better than the new design.

On the install page I'd prefer to have the information from http://ocaml.org/releases/,
perhaps structured with menus like on http://ocaml.org/install.html.
The default tab could be 'Source', and it should show how to download and install the latest _stable_ release from source (4.01.0 now).
The release notes should be visible in the common area, and binary packages accessible from menus or links.
It is fine if instructions on accessing the SVN (or github mirror) is hidden behind a menu / link, I think it is more important to advertise the stable source tarball.

Also it'd be nice if a checksum of the source tarball would be available (even if not digitally signed, but of course a digital signature would be even better).

**Comment by dbuenzli** [comment]
Yesterday I came to this page to install ocaml on ubuntu and I found it incredibly noisy and disapointing.

Here are a few suggestions: 

I think that, if their authors agree, we could kill some of the alternatives to opam mentionned in the multi-platform packger managers and rename the section. These are: 
- `oasis-db` /cc @gildor478 
- `odb` /cc @thelema (I fondly remember that one, happily used it at some point, seems another life)

Regarding `ocamlbrew` (@hcarty), it still seems active and to be an alternative way to install `ocaml` and `opam`, maybe a few words should be said about it if kept on the page. Especially whether this is really a package manager or not, my impression is that it's not.

Remove in general install instructions for third-party libraries, this should be about how to install ocaml and/or opam (why would I install `ocaml-xml-light` on Maegia and not on SuSe ? or `cryptokit` if I'm using `macports` but not in any of the other cases ?)

Remove in general random and useless chitchat (e.g. "Homebrew is a new and upcoming package management system for Mac OS X and has a very large community", "FreeBSD had a great support for OCaml development for a long time. ") . Get to the point, install the fucking camel and its package manager on this platform/setup possibly linking on how to get a setup (e.g. link to homebrew install instructions instead of describing that it needs bash and xcode to install...).

Some of tips about modes and documentation on the page should be linked to a seperate page on how to setup a development environment.

**Comment by dbuenzli** [comment]
> Here are a few suggestions

The suggestions are implemented in PR #829.

**Comment by hcarty** [comment]
Regarding ocamlbrew, it is definitely not a package manager.  Its primary purpose at this point is to help bootstrap `opam` when packages/binaries are not otherwise available.  Any other features it used to provide are better handled by `opam`.

**Comment by dbuenzli** [comment]
@hcarty I removed it from my proposal. I think it would be better mentioned in opam's own instructions /cc @AltGr. What do you think ?

**Comment by hcarty** [comment]
@dbuenzli I think that's entirely reasonable

**Comment by dbuenzli** [comment]
Well in fact it's already there https://opam.ocaml.org/doc/Install.html#Usingocamlbrew

**Comment by gildor478** [comment]
oasis-db -> yes you can remove it. It is deprecated.
