### ISSUE TITLE
add robots.txt file to preview.ocaml.org

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#276]
We should insert a robots.txt file for the preview version of our site. Although I currently see it showing up only in my personalized Google search results, there is a risk of links to it showing up for others.

**Comment by amirmc** [comment]
We could but since we're so close to the final release I'm not sure if it's worth it.  We'd have to remove it on Tuesday anyway.

**Comment by avsm** [comment]
Isn't preview going to be the ongoing staging site? It would be useful to act as such even after we go live.

**Comment by amirmc** [comment]
I was going to treat the VM as the the live site and you were going to point the `ocaml.org` domain at it -- otherwise we're still using GitHub to serve the pages. See deployment steps on #184 (I've just named you on the DNS step).

D'you have a different idea of what the the workflow should be like?

**Comment by avsm** [comment]
Two VMs then, one of which is running preview and one live.

**Comment by pw374** [comment]
If we care a lot about _page-rank et al._, we should put a robots.txt preventing any indexation for preview.ocaml.org.

**Comment by agarwal** [comment]
I was assuming we were keeping the domain preview.ocaml.org (or some variant like staging.ocaml.org) for ongoing work. But also we are considering using Travis, which if I understand correctly, allows any fork of a repo to get built and viewed. In that case, maybe we wouldn't need a preview domain.

**Comment by pw374** [comment]
Ongoing work shouldn't be indexed by robots, because as far as I understand it it's harmful to have a duplicate of another site (just as it's harmful to serve a site on both www.domain.ext and domain.ext if they serve the same contents).

I don't think Travis can host a website, I believe it can build it, and then put it somewhere, but it'll only keep the records of the build process. (Please correct me if I'm wrong.)

**Comment by agarwal** [comment]
We could also keep using the gh-pages branch. The former `make publish` command could be renamed to `make preview`. When we remove the CNAME file, this site would only be visible under the github domain. Just an idea.

**Comment by pw374** [comment]
> We could also keep using the gh-pages branch. The former `make publish` command could be renamed to `make preview`. When we remove the CNAME file, this site would only be visible under the github domain. Just an idea.

I agree. But then that depends on how often the site is built and how Github takes it. (Sometimes Github fails to synchronise correctly and we end up having a website in a weird state.)

**Comment by pw374** [comment]
But, as Anil mentioned we could have 2 VMs, I guess the newer one can host http://ocaml.org and the current http://preview.ocaml.org one can host http://staging.ocaml.org.

**Comment by amirmc** [comment]
Folks, I made a separate issue to discuss this #277

**Comment by agarwal** [comment]
This has been done in ba5b79a52c67b14aea03bb619f68b1eeacdee358. Closing the issue.
