### ISSUE TITLE
Jamie Brandon's blog should probably be removed from the planet feed

### ISSUE THREAD

**Issue by yminsky** [ocaml/v2.ocaml.org#333]
It seems to be mostly about Clojure these days...

**Comment by Chris00** [comment]
In the same vein, the [Planet subscription HOWTO](http://www.ocamlcore.org/planet/) may need
- to be ported to ocaml.org
- to be updated.

**Comment by agarwal** [comment]
We could change it to only his posts tagged `OCaml` (as I do for my own blog). The URL would be:
http://scattered-thoughts.net/blog/categories/ocaml/

**Comment by amirmc** [comment]
I don't see anything obvious in the feed that would allow it to be easily filtered.  The atom feed is for the whole site.

We have three options: (a) remove the feed, (b) ask Jamie for a specific feed for ocaml related posts or (c) figure something out ourselves to filter the posts.

I'm inclined to do (a) and maybe (b), but since he hasn't tagged a post  with `ocaml` in almost a year, I wouldn't expect a response.  I see no value in doing (c).

As such, I've opened an issue on ocamlcore [1] to remove the feed.

[1] https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1350&group_id=1&atid=101

**Comment by pw374** [comment]
This seems to work:

http://scattered-thoughts.net/blog/categories/ocaml/atom.xml

**Comment by amirmc** [comment]
I stand corrected! I added a comment on the ocamcore issue to state that the feed should be updated.

**Comment by amirmc** [comment]
This was fixed some time ago.
