### ISSUE TITLE
Events list on Community Page isn't chronological

### ISSUE THREAD

**Issue by dsheets** [ocaml/v2.ocaml.org#361]
Right now says

```
OCaml 2013
24 September 2013
Announcement

NYC Functional Holiday Party
9 December 2013
News

OCaml Users in Paris
9 October 2013
News

Cambridge NonDysFunctional Programmers
18 September 2013
News
```

Is it supposed to be in this order? Also, the "Announcement" event for OCaml 2013 is bolder/darker colored and looks sorta weird.

**Comment by agarwal** [comment]
List items marked as announcements are considered more important. They are supposed to come first and have an icon that is darker, so they stand out more. Other items come next. Within both categories, the items are supposed to be in reverse chronological order. Thus, I think everything is correct. Let me know if I missed something.

**Comment by agarwal** [comment]
I'm assuming this was closed because my explanation was considered correct. Okay, I agree.

**Comment by samoht** [comment]
I tend to agree with David here. Use a different color scheme if you want to differentiate key events, but keep at least a (chro)logical order.

**Comment by agarwal** [comment]
Okay, so re-opening. The proposal is requesting two changes:
1. Keep all events in chronological order (not in reverse chronological, and not in two separate categories).
2. Highlight key events with a different color rather than a different icon.

I'm okay with 1 since the list is short. However, reverse chronological still makes more sense to me on the full [meetings](http://ocaml.org/meetings/) page when the list gets long.

Not so sure about 2. The alternate icon also stands out, so I'm okay just having that as the distinction. We'd have to try some specific styling to see if something looks better.

**Comment by Chris00** [comment]
I think it would be better to keep the reverse chronological order as the two other lists.

Mabybe we also want to start to generate the feed from a CSV file (importance, name, date, URL)?

**Comment by samoht** [comment]
sorry, I wasn't very clear, but I meant reverse chronological order. And after some thoughts, keeping the different icons as it is should be enough.

**Comment by agarwal** [comment]
Okay, so only remaining question is if we should have two separate categories: all announcements come first followed by all regular events. Or just merge into one list, with the different icon sufficing to emphasize the announcements.

**Comment by Chris00** [comment]
I am fine with either.

> Okay, so only remaining question is if we should have two separate categories:
> all announcements come first followed by all regular events. Or just merge into
> one list, with the different icon sufficing to emphasize the announcements.

**Comment by agarwal** [comment]
Okay, so I'm leaving this as-is. The main issue with this list is more significant, that it isn't auto-generated from various feeds. That's a separate issue.
