### ISSUE TITLE
provide official logos

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#44]
Provide official OCaml logos. Use Inria's [logos](http://caml.inria.fr/resources/logos.en.html) page as a starting point, but these are actually using the old name Caml. Someone updated these to "OCaml" and posted somewhere; search mailing list.

**Comment by Chris00** [comment]
Done. b6fdad0a6d51d50fff34621d984208a4704e04a0
http://ocamlweb.forge.ocamlcore.org/www/logos.html

This page is not referred from anywhere now.  I think we have to ask INRIA for official __O__Caml logos...

**Comment by Chris00** [comment]
Inria request: http://caml.inria.fr/mantis/view.php?id=5751

**Comment by agarwal** [comment]
How about we create a new Etc menu, but this doesn't get copied to a
section on the front page. Then, we can put links to random other things in
this menu. Let me know if you like the idea.

**Comment by Chris00** [comment]
I am not against (I would rather adopt "Misc") but I think it is a short term solution — I would hope things eventually find their "natural" place.

**Comment by agarwal** [comment]
I agree that a Misc menu is the lazy way out. Maybe we need an "about"
page, which gives basic information about who develops ocaml, what's the
website itself about, who develops the website, etc. I think a link to the
logos page from an about.html page could make sense.

**Comment by Chris00** [comment]
Sounds OK to me.  Add the rencently uploaded pages "A History of OCaml". 96c9837bc34f94587fc6cec9fe280d230a021ef6

**Comment by Chris00** [comment]
Maybe the location of the bug tracking system could be on that menu too?

**Comment by agarwal** [comment]
For now I created a new More menu (sounded better than Etc and Misc) and
added the logos link there. I'm not yet sure what to put on an About page,
so we can leave that idea for later.

**Comment by agarwal** [comment]
Logos link added to More menu in
commit 3953556aeea7c96a3f867f3563a758534dc1e666. Not closing this Issue
yet, as we still need to await reply to request submitted to Inria for
official updates to the logos.

**Comment by agarwal** [comment]
Note also that OCaml Labs is having a new logo professionally designed. The aim is to make this new logo the universally recognized symbol for OCaml.

**Comment by avsm** [comment]
CCing @amirmc so he can update this issue re: the logo sketches when they arrive.

**Comment by amirmc** [comment]
Hi folks, just to let you know that a logo for OCaml is one of the aims of the design work for ocaml.org.  You can now see the first draft in the wiki at https://github.com/ocaml/ocaml.org/wiki/Draft-OCaml-Logos

If you have any feedback, please do let me know.

**Comment by amirmc** [comment]
Relevant to #113

**Comment by dbuenzli** [comment]
Some feedback on the draft logo.
- I think it would be better for the default logo to use the monochrome scheme used by ocaml-labs on github. It maximises the chances of the logo to look right in any context. [1]
- I like the use of negative space however when put in context it can feel a little bit ungrounded (e.g. see at the bottom of [this](http://opam.ocamlpro.com) page) instilling the idea that  OCaml is build on a pile of sand... Maybe (?) this can be fixed by lowering the leftmost dune at the level of the right-most one, to reinforce a more horizontal line. 
- The font is _terrible_, it has a feeling of comics sans to me, it's a font for toys. Something more firm and settled is needed (no serifs, no italics or oblique) implying OCaml's solid foundations.

[1] A logo generator to accomodate a color scheme could be an idea btw. Should eventually be doable with [Vg](http://github.com/dbuenzli/vg) and canvas's `toDataUrl` if I can get the logo path outlines and gradient specification.

**Comment by amirmc** [comment]
@dbuenzli Appreciate the feedback, thanks!
- Logo colour - I think we do need a colour one and it should be the default one. There will also be a monochrome variant (as you've noticed) and other variants where the camel is either 'cut-out' or white.  The idea was to work towards something that can be distinctive, rather than maximising the odds of looking ok in different contexts (too difficult to achieve).
- Negative space - I don't really agree about it being 'built on sand' (I think that's just you).  However, there is a version where the camel is white, which may be more appropriate for certain contexts.  Will think about the sand dunes though and maybe whether we should 'enclose' the image to make it more 'grounded'.
- Typeface - I quite like the font but you're not the only person to have mentioned it.  I'll bring this up with the agency next time we look at it (after the site-design work is mostly done).
- Logo generation - People will be able to do pretty much as they please with the logo so I'm aware of this possibility.  I haven't made SVG files public yet as we're not at the final version (there have already been minor iterations since I posted the draft).  However, I'm perfectly happy to send you a copy by email if you want to play around.  Let me know by email.

**Comment by dbuenzli** [comment]
Default logo color, maybe you are right after all a logo should be made to scream ME! ME! ME! ME! 

Keeping it monochrome (in the sense one color) as it is now is nice though as it allows to easily match it to other color palettes (if the logo generation idea is to be taken).

I'm not sure about what you mean by another version where the camel is white or cut-out. In any case I really think it's better if there's a _single_ logo, a _single_ shape and the usage guidelines should just hint at sky color changes. 

In my opinion framing/enclosing the image to make it more grounded would defeat the negative space idea. There are already to many frames, lines and boxes on the web. I think you should strive to make it grounded by keeping the same idea as it is now, by playing with white space. I'm almost sure you can get to that by tweaking that bottom horizon line -- for me the extreme left part of the horizon line is going too far up and since there's already a lot of white because of the caml above, my brain loose the implied invisible frame there.

**Comment by amirmc** [comment]
> Default logo color, maybe you are right after all a logo should be made to scream ME! ME! ME! ME!

Indeed :)

> Keeping it monochrome (in the sense one color) as it is now is nice though as it allows to easily match it to other color palettes (if the logo generation idea is to be taken).
> 
> I'm not sure about what you mean by another version where the camel is white or cut-out. In any case I really think it's better if there's a single logo, a single shape and the usage guidelines should just hint at sky color changes.

I do know what you mean but it's better to make variants available for common use-cases.  Specifically, light vs dark backgrounds.  We found that having the 'alpha' camel on certain backgrounds (e.g textured) just looked a bit strange but a non-alpha (i.e white coloured) camel looked ok.  I've added another png to the wiki to make this clearer (it won't be obvious on the page itself due to the white background - save it and open it elsewhere).  

I'm perfectly happy to have logo generation if that's what people want but it isn't something I'll be co-ordinating (mainly due to time/priorities).  All SVG files will be made publicly available so the community can do whatever it wants with them (if anyone would like the draft files sooner, I'm happy to send them on request).

> In my opinion framing/enclosing the image to make it more grounded would defeat the negative space idea. [...] I'm almost sure you can get to that by tweaking that bottom horizon line -- for me the extreme left part of the horizon line is going too far up and since there's already a lot of white because of the caml above, my brain loose the implied invisible frame there.

Yes, I can understand what you're seeing now.  We'll revisit this once the site design stuff is well underway and I'll get in touch with you explicitly.

**Comment by amirmc** [comment]
Closed by accident.

**Comment by dbuenzli** [comment]
Le mardi, 26 mars 2013 à 16:49, Amir Chaudhry a écrit :

> We found that having the 'alpha' camel on certain backgrounds (e.g textured) just looked a bit strange but a non-alpha (i.e white coloured) camel looked ok. I've added another png to the wiki to make this clearer (it won't be obvious on the page itself due to the white background - save it and open it elsewhere).

Ah right, I understand now, this feels right. I was fearing that it was a variant with another "shape", which would be bad. A single shape should to be deeply imprinted in everybody's brain.  

Daniel

**Comment by agarwal** [comment]
@amirmc Do you have final versions of the new logos? The [logos](http://ocaml.org/docs/logos.html) page has the old logos, which are not modern looking. Just providing the new marque with and without _OCaml_ next to it, and in various sizes, should be sufficient. We certainly don't need the _ocamldoc_ variants.

**Comment by amirmc** [comment]
I need to get in touch with the design firm for the final round of edits and feedback.  Once they're done, I'll post here and close off this thread (assigned this issue to myself so I don't forget).

**Comment by pw374** [comment]
Do we have any news concerning the logos?

**Comment by amirmc** [comment]
Yup. I asked the design firm about this recently and we have the RC1 of the OCaml branding.  You can see it at:
https://github.com/ocaml/ocaml.org/wiki/Draft-OCaml-Logos

I'm happy to accept this as the final version so the only thing left is to get the assets in the appropriate form (i.e. SVG, monochrome, etc).

**Comment by amirmc** [comment]
@agarwal just noticed your last comment about what formats we need.  Can you list them? (or edit this comment to include them all)
- [ ] SVG, PNG, JPG
- [ ] Colour and Greyscale
- [ ] with and without text
- [ ] Retina/web version (I think there are 3 formats here?)

If I multiply those all up, that comes to about **15** files we're expecting.  Am I right? (the web versions are only JPG)

**Comment by agarwal** [comment]
I'm not sure what formats are needed. How about asking the design firm themselves. They should know. I would push for the most raw format possible, e.g. if they made the images in Photoshop, get the PSD files.

**Comment by lpw25** [comment]
Do we have the logo in the required formats now? If so could we update (http://ocaml.org/docs/logos.html) to list the new logos instead of (or at least more prominently than) the crappy old ones.

**Comment by Chris00** [comment]
We [have them](https://github.com/ocaml/ocaml.org/wiki/Draft-OCaml-Logos) but the question is where to host them.  They should **not** be in the ocaml.org repo and the other members are not keen to put them in ocaml.org-media.  Maybe one can just drop them in a (non-versioned) folder on the site?

**Comment by amirmc** [comment]
Did we mention having an ocaml.org-logo repo? It would be visible online and cloning that repo would give access to all the images and we could tag a release so that they could be taken as a tarball.

**Comment by agarwal** [comment]
I'd go with creating an ocaml-logo repo (not ocaml.org-logo).

**Comment by amirmc** [comment]
> ocaml-logo repo

ofc, that makes way more sense.
repo is up (but not initialised) at
https://github.com/ocaml/ocaml-logo

I'll push the images I have in a few moments.

**Comment by amirmc** [comment]
Repo now up!  URLs are of the form:
https://raw.githubusercontent.com/ocaml/ocaml-logo/master/$PATH-TO-FILE

@Chris00 could you take a look and make sure this is what you were expecting? We should add license info before we tag a release.

**Comment by Chris00** [comment]
The bounding box of the SVG version should be tight — I had to do that for the navbar SVG logo.  One a license and a tag-generated-tarball are added to the repository, the page should be modified to refer to them.

**Comment by Chris00** [comment]
An orange colored SVG version should also be provided.

**Comment by agarwal** [comment]
Should your last two points be added as issues to the ocaml-logo repo?

**Comment by Chris00** [comment]
@agarwal Yes: https://github.com/ocaml/ocaml-logo/issues/1 https://github.com/ocaml/ocaml-logo/issues/2 https://github.com/ocaml/ocaml-logo/issues/3
