### ISSUE TITLE
Clarify usage of `;;` and `;` in OCaml code

### ISSUE THREAD

**Issue by amirmc** [ocaml/v2.ocaml.org#450]
This seems to be a source of confusion.
@talex5 pointed me at threads like [1], where the usage is misunderstood.  The content on the website is also confusing [2].  Is it really this complicated?

I'm aware that we have an issue in our code examples where we put things through the toplevel (and therefore need the `;;`) but other code that is just syntax highlighted should be more idiomatic.

[1] https://news.ycombinator.com/item?id=7416328
[2] http://ocaml.org/learn/tutorials/structure_of_ocaml_programs.html#Usingandomittingand

**Comment by pw374** [comment]
http://ocaml.org/learn/tutorials/structure_of_ocaml_programs.html#Usingandomittingand is confusing. Things are not that complicated.

`top-level expression;;` <-- `;;` is mandatory

`top-level definition;;` <-- `;;` is optional

Ideally, in "real" software, one should not use `;;` at all, and that's it.
(It implies that one shouldn't write any top-level expressions in real software.)

Then, a "top-level definition" is a let binding (not a let-in binding), a type definition, a module definition, a module type definition, or a class definition. (And I hope I'm not forgetting anything.)
And a top-level expression is a value or at least it has the type of a value (an instance of a type such as 4, {contents=42}, ["foo"], "bar", `Foo, (object method x = 42 end), (let ... in ...),  (raise Not_found <-- this one is not a value, since it doesn't terminate, but has the type of a value), ...).

---

In the top-level loop (i.e., `ocaml` on the command line), when it sees `;;`, it evaluates everything that precedes it, so one can't escape having to write `;;` at some point when using it. But the top-level loop is not meant for real software, it's only meant for teaching/learning and rapid testing.

**Comment by pw374** [comment]
The contents of https://news.ycombinator.com/item?id=7416328 is mostly like (non computer scientists) politicians talking about computer science. Most of them just don't know what they are talking about. And indeed http://ocaml.org/learn/tutorials/structure_of_ocaml_programs.html#Usingandomittingand is not helping.

**Comment by amirmc** [comment]
I think that thread is just one example of where people may be confused but it's difficult to point them at correct information until our own content has been triaged.  People will always be wrong on the internet but we can make our own corner more correct :)

**Comment by pw374** [comment]
On 01 Apr 2014, at 15:30 pm, Amir Chaudhry notifications@github.com wrote:

> I think that thread is just one example of where people may be confused but it's difficult to point them at correct information until our own content has been triaged. People will always be wrong on the internet but we can make our own corner more correct :)

I concur.

(But it’s going to take time...)

**Comment by Chris00** [comment]
Done in the commit 002a3fb04eaa9abfef85f05fa099e31cb2ae2376 and those in the merged branch.

**Comment by Chris00** [comment]
The text can certainly still be improved but it is much better than before.
