### ISSUE TITLE
Headings with id attributes disappear

### ISSUE THREAD

**Issue by dsheets** [ocaml/v2.ocaml.org#523]
https://github.com/ocaml/ocaml.org/blob/master/site/css/bootstrap_mod.css#L24 causes new `h4` elements in `well` divs, e.g., to disappear under the div. I don't understand what styling issue this rule was intended to fix but setting `z-index` based on presence of the `id` attribute seems perverse.

**Comment by Chris00** [comment]
The headers with an ID can be hyperlinked to.  When one clicks on such a link, we do not want the header to disappear under the navigation bar.  The trick used is:

```
padding-top: 75px;
margin-top: -75px;
```

But then the problem is that hyperlinks that occur just before the header cannot be clicked because they are under the header box.  The `z-index` property solves that.  If you have an alternative — less hacky — solution, please propose it.

**Comment by dsheets** [comment]
I don't have an easy way to reproduce this at the moment. I wonder about using the `:target` pseudoselector to only do the `padding-top`/`margin-top` trick when the anchor is active.

As for the `z-index` issue, there may be some way to discriminate between "background" elements and "foreground" elements so that the anchor can be made to be below other content but not below boxes.

Finally, we could post-process the site so that all header anchors have their anchor lifted to an enclosing element without content but which can be styled with the appropriate top padding to account for the fixed nav bar.

**Comment by Chris00** [comment]
Using the `:target` selector is a good idea.  I [did it](https://github.com/ocaml/ocaml.org/commit/1f259773e011c6323cdb87e49dbaa268ed4a77b9).

**Comment by Chris00** [comment]
@dsheets Anything left to do?

**Comment by dsheets** [comment]
I don't know. This is probably safe to close.
