### ISSUE TITLE
Adding mads379.github.io to the aggregator

### ISSUE THREAD

**Issue by mads-hartmann** [ocaml/v2.ocaml.org#581]
Hi,

I've been using OCaml for about a year now and I've started to condense some of my various notes into a series of blog posts on OCaml.

name: Mads Hartmann
url: http://mads379.github.io/feed.ocaml.xml 
type: personal

The RSS feed linked will only contain blog posts that are  categorised as OCaml :)

Cheers,
Mads

**Comment by amirmc** [comment]
Thanks! I'll get this added shortly.

**Comment by amirmc** [comment]
Upstream [issue created](https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1440) and the local branch also updated (https://github.com/ocaml/ocaml.org/commit/13a0c39a7688e6aa75f14a5fc5566066779b0f87). Leaving this open until upstream is closed.

Mads, just to explain, we're in a transitory phase while we finish up work on our own implementation of the aggregator feed (in the `syndic` branch). Hence the multiple links above so that other maintainers can keep track.

**Comment by mads-hartmann** [comment]
Awesome, and thanks for the clarification :)

**Comment by amirmc** [comment]
Closed upstream and now visible in the feed (e.g http://ocaml.org/community/planet/#0a83979220a0e6e26936e343c8475213).

**Comment by mads-hartmann** [comment]
Great, thanks a lot Amir

**Comment by dbuenzli** [comment]
There's a problem with the feed links. It generates double dashes which lead to 404

http://mads379.github.io//ocaml/2014/11/15/ocamldebug.html

**Comment by amirmc** [comment]
Well spotted but it doesn't 404 for me.  I've made a new issue on the [forge](https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1441).

**Comment by amirmc** [comment]
@mads379 the problem is in your feed (I should have checked before assuming it was a planet issue).  

If you inspect the xml [1] you'll see that the `<link>` and `<guid>` tags have the double slashes. Can you fix this?  I'll close this issue once you report back.

[1] http://mads379.github.io/feed.ocaml.xml

**Comment by mads-hartmann** [comment]
@amirmc Sorry about that, should be fixed now

**Comment by amirmc** [comment]
Yup, all looks good to me.  Thanks!
