### ISSUE TITLE
Add a 4.02.1 page.

### ISSUE THREAD

**Issue by Drup** [ocaml/v2.ocaml.org#592]
Would it be possible to add a page http://ocaml.org/releases/4.02.1.html ? Currently there is http://ocaml.org/releases/4.02.0.html and http://ocaml.org/releases/4.02.html only. 4.02 should be a symlink to 4.02.1.

Also, I think a symlink /latest would be nice.

**Comment by agarwal** [comment]
Using X.Y.Z as notation for the version numbering, note that what I did was to list every X.Y.Z in `releases/index.html`. However, I started to ignore the Z starting with 4.02, so both 4.02.0 and 4.02.1 point to 4.02.html. I had decided that that's the correct pattern to follow because Damien's release notes do not change upon a change in Z. The entire contents for 4.02.0.html and 4.02.1.html would be nearly identical except for the first sentence. However, that's not what you proposed. Let me answer the questions you did ask:

> Currently there is http://ocaml.org/releases/4.02.0.html

I see. Actually, this is a build remnant. That page used to exist, but I deleted it from the repo and our build system isn't smart enough to delete files that should no longer be generated. I just manually deleted it.

Are you happy with that solution or do you think URLs should exist for every full X.Y.Z version?

> 4.02 should be a symlink to 4.02.1.

Okay.

> Also, I think a symlink /latest would be nice.

Okay.

**Comment by amirmc** [comment]
To add to Ashish's point, I'd note that there's only one linked change log for the 4.02 series [1] (though obviously it does separate the 4.02.0 and 4.02.1 changes).  The folder structure itself [2] follows the X.Y format so I'd be inclined to stick with that for OCaml.org.

As such, I wonder that we should stick to X.Y references on the releases page too.
- [1] http://caml.inria.fr/pub/distrib/ocaml-4.02/notes/Changes
- [2] http://caml.inria.fr/pub/distrib/

**Comment by Drup** [comment]
> I see. Actually, this is a build remnant. That page used to exist, but I deleted it from the repo and our build system isn't smart enough to delete files that should no longer be generated. I just manually deleted it.

This is not a good idea, it creates dead links for various people that relinked the announcement, which is very bad and is, for example, the case of the topic in the IRC channel.

**Comment by amirmc** [comment]
Having said that. 4.02.0 is still available via opam so I think it should be mentioned (briefly) on the 4.02.1 page (something like "4.02.0 was released on dd-mm-yy").

**Comment by Drup** [comment]
I personally don't care all that much about X.Y.Z existing. Adrien, which is the IRC mod and the one who pointed out the inconsistency, seems to care a lot. :)

I do care about dead links, though.

**Comment by amirmc** [comment]
> > I see. Actually, this is a build remnant. That page used to exist, but I deleted it from the repo and our build system isn't smart enough to delete files that should no longer be generated. I just manually deleted it.
> 
> This is not a good idea, it creates dead links for various people that relinked the announcement, which is very bad and is, for example, the case of the topic in the IRC channel.

Good point. We should avoid breaking links for the release pages, especially as these are the ones we're likely to circulate widely (or at least try to), when new versions are available.  Removing a page would then involve setting up a redirect, which is more awkward to maintain.  Perhaps we should do that in this case and then stick to X.Y from now on.  This assumes that OCaml version numbers are consistent (e.g that minor releases actually are minor).

TBH I'm just thinking aloud here.

**Comment by Chris00** [comment]
> build system isn't smart enough to delete files that should no longer be generated. I just manually deleted it.

It should.  Since the site is rebuild from scratch every couple of hours, we must make sure to use `rsync -av --delete --delete-after ...` when pushing the site.  This may be part of https://github.com/ocaml/ocaml.org/issues/532
However, I agree it is generally a good idea to transform the page into a _redirecting page_ instead of removing it.

**Comment by agarwal** [comment]
I pushed a fix in ebf89603b87c78669da0240f4595222fef318593. I'll close this issue unless someone says something else should still be done.

**Comment by Drup** [comment]
What about the "latest" symlink ?

**Comment by agarwal** [comment]
Done here: 249a1cef9609e79e046f392eefe136edc8b77a47.

**Comment by Drup** [comment]
Nice, thanks.
