### ISSUE TITLE
add Pumgrana to companies page

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#602]
http://pumgrana.com/

**Comment by Chris00** [comment]
Did you contact them to have a logo & description?

**Comment by agarwal** [comment]
No, I didn't contact them. I've started assuming we should make the content ourselves. In the past, it's always taken too long to get replies from a company representative.

**Comment by Chris00** [comment]
It [looks](http://54.148.96.182/blog/a-propos/) more like an open source project than a company so far.

**Comment by amirmc** [comment]
The link Christophe posted appears to be broken now.  I found my way to the following.
- https://github.com/Pumgrana
- http://blog.pumgrana.com

The pages are French but after putting a post through Google Translate I find: "Pumgrana is an open-source browser engine project".  Since it's not a company, I'm closing this issue.
