### ISSUE TITLE
Content needs update: current official version is 4.00.1

### ISSUE THREAD

**Issue by lefessan** [ocaml/v2.ocaml.org#61]
The current official version is 4.00.1, but the website still says it is 4.00.0.

I would have updated it myself, but the website has too many dependencies, even for opam (webrizer >= 0.7.1 !!!).

**Comment by samoht** [comment]
I've just added 0.7.1 to opam

**Comment by agarwal** [comment]
Fixed in commit a1fd17f6775c9c099c609b4d33202329e20b58e5, 3737fb331411165e993a36789a59819fd30e7e2a, and 7b9d1c180b53f2e5f101495c599e41a57a08a934. Regarding too many dependencies, please discuss on the mailing list with ideas you might have to simplify it. I don't know how without losing substantial functionality.
