### ISSUE TITLE
Google Archive of Caml Mailing List not Up to Date?

### ISSUE THREAD

**Issue by lindig** [ocaml/v2.ocaml.org#699]
The website points to Google Groups for the mailing list: [fa.caml](http://groups.google.com/groups?group=fa.caml). From my point of view, the latest posts there are from July 2015, suggesting the the archive is not kept up to date. If so, I think it either should be fixed, mentioned as incomplete, or the link be removed.

**Comment by agarwal** [comment]
This is currently being discussed in a thread on the OCaml List.

**Comment by amirmc** [comment]
Just for info, the thread starts at: https://sympa.inria.fr/sympa/arc/caml-list/2015-09/msg00024.html

I’d be in favour of mirroring the list to lists.ocaml.org somehow.  I believe this has been discussed before but no-one has had time to look into it.

**Comment by lindig** [comment]
I think a more useful archive and interface than Google Groups is at [GMANE](http://dir.gmane.org/gmane.comp.lang.caml.inria). It provides a good web interface, as well as RSS and NNTP interfaces. It also seems to be up to date. I'd suggest to replace the link.

**Comment by Chris00** [comment]
> The website points to Google Groups for the mailing list: fa.caml.

In my opinion, none of these should be on the website — the threads are not complete.  The interface of the mailing list at Inria may not be the easier one to deal with but it is the authoritative archive.

**Comment by gasche** [comment]
@Chris00 invited me to share my pain points with the current Sympa interface here. I see three basic needs for mailing-list archives:
- Need 1: User is not currently subscribed to the list but want to have a look at how the OCaml community is doing lately. They need a reasonable way to have a look at recent discussions and follow a particular conversation they are interested in. (I do that myself with, say, llvm-dev or lkml). Most mailing-list archive browsing software will do the job there, and I think the current Sympa instance, if we removed the irritating paging and just listed the topics of the month, would do fine (we have to check that it's easy to follow a thread across two different months, that may be an extra pain point)
- Need 2: User remembers a particular message or thread that they want to link for reference. They need a way to search this message back in the archive. The Sympa search feature is completely broken for this purpose (I guess Google archives is better, but a well-indexed non-Google archive could do the job fine; I just sent a message to caml-list to ask to change robots.txt to allow indexing). As a second choice, suppose the user found the thread back in their mailbox, it should be very easy to find a thread from its precise title or its date (something the Sympa paging currently makes much more bothersome than it needs to be).
- Need 3: User wants to know about a specific OCaml topic by looking at relevant conversations in the mailing-list archives. (For example: "opam windows"). Again, this is a matter of either having a good internal search (but this is a lot of work) or being indexed well by third-party search engines (which users are more likely to use as their query interface anyway).

**Comment by agarwal** [comment]
I feel the Google archive meets all 3 of the @gasche's needs, which is why I'm still supportive of it. These needs sometimes fail only because every now and then messages stop getting mirrored there, which should should be fixable (if I can get admin access).

**Comment by gasche** [comment]
I personally dislike moving more and more of our core infrastructure to proprietary codebases, so I will not use Google Archives or promote its use by using its URLs to refer to caml-list discussions, and am interested in pushing for improvements using free-software platforms (Gmane, Sympa, Mailman) independently of Google archive's quality. Of course, the more usable archive mirrors the better, in particular when the current count is zero.

**Comment by Chris00** [comment]
As @gasche, I think that it would be better to use open source software if possible.  We haven't yet explored enough whether we can improve the situation using the Inria mirror.  We should give ourselves a bit of time—after all the Inria archives have been linked for more than a year and the debate only takes place now.  I do not think there is any rush.

**Comment by nilsbecker** [comment]
since there was a new discussion on the mailing list mentioning this, here my personal experience: when i got into ocaml a few years ago, i looked for a google group and found fa.caml. however, many posts auto-expired and were not archived for more than 2 weeks. still, the list looked alive. then i wrote to the list and never got any answers -- i did not realize that this was effectively a read-only mirror of the actual list. this fact was also not mentioned anywhere on the google groups interface. in short, the worst possible experience. at present, it's at kind of obvious that this is a zombie group but still may give the impression to a very casual onlooker that ocaml were dead.  this google group should go away.

**Comment by dbuenzli** [comment]
> I feel the Google archive meets all 3 of the @gasche's needs, which is why I'm still supportive of it.

Frankly the google archive UI is terrible and expires messages. The `sympa` mailing list software is everything but this, I'd even say that in the current form, I feel personally insulted by it.

Why can't we simply link to http://news.gmane.org/gmane.comp.lang.caml.inria. At least it has the archives from almost the beginning, a reasonably functionning search capability and a less broken UI than everything that exists out there (I think it correctly links threads across months which IIRC is something most mailing list archiving software out there is not able to do in 2016).

Also a link to the curated mailing list (a.k.a. [OCaml Weekly News](http://alan.petitepomme.net/cwn/)) should be added.

**Comment by agarwal** [comment]
I agree with all points made. Anyone care to submit a pull request?

Regarding the google group, sounds like it is only doing harm. Anyone know who owns it? We should either shut it down and/or include a message at the top of the group's page explaining that it isn't a reliable interface. Being able to send messages to that group is especially terrible. All this can be fixed by the way. See e.g. the [biocaml mirror on google groups](https://groups.google.com/forum/#!forum/biocaml), in which I've made the correct settings such that none of this happens.

**Comment by gasche** [comment]
So the maintainer of Gmane just announced that [it would close real soon](https://lars.ingebrigtsen.no/2016/07/28/the-end-of-gmane/), which is a setback as I just added a link to the Gmane archives in #802. This closing post references [The Mail Archive](https://www.mail-archive.com/) as a good alternative, and they seem to have an mbox import ability, so that could be a choice for an alternative archive -- which gets us back to the need of getting mbox imports from the past and current archives.

**Comment by UnixJunkie** [comment]
I subscribed the mail archive to caml-list. It has some messages but I'm not sure they have all of the past ones. We should try to import all old ones. I.e. we need to have access to the sympa's caml-list archives in mbox format.

**Comment by Chris00** [comment]
@UnixJunkie can [mail archive](https://www.mail-archive.com/) import a mbox?  If so, I think @xavierleroy can provide one with all past messages.  If it's a different format, @dinosaure may be able to do the translation.

**Comment by UnixJunkie** [comment]
@xavierleroy to import an mbox file, you need to provide the mbox file to themailarchive@gmail.com .
It is the email of the support team.

**Comment by UnixJunkie** [comment]
someone just proposed this on caml-list:
https://inbox.ocaml.org/caml-list
Maybe, this will allow to close this issue.

**Comment by agarwal** [comment]
I agree. This issue is no longer relevant. #802 already removed the link to the google archive. I've created #967 to request listing the new https://inbox.ocaml.org/caml-list archive.
