### ISSUE TITLE
"Community" link gives an empty page

### ISSUE THREAD

**Issue by slegrand45** [ocaml/v2.ocaml.org#705]
In the top menu, the community/communauté link ( https://ocaml.org/community/ or https://ocaml.org/community/index.fr.html ) gives an empty page.

**Comment by amirmc** [comment]
Thank you for the report!

Explicitly navigating to https://ocaml.org/community/index.html doesn’t show the page so I wonder if something happened on the VM.  Building things locally seems to be fine.

I believe the site is rebuilt from scratch every hour so it may clear itself up.  @pw374 @Chris00 @avsm @agarwal, if you have a moment and can access to the VM, perhaps you can force a rebuild sooner?

**Comment by agarwal** [comment]
I'm checking it now. The file is empty for some reason. The new build is currently running, so let's see if it fixes itself.

**Comment by agarwal** [comment]
One problem fixed. We had an opam conflict with ocamlgraph, so the builds were failing. This was resolved by running `opam upgrade --fixup`. Now the build succeeds, but it keeps generating an empty `community/index.html` file. Still investigating.

**Comment by agarwal** [comment]
The following command within `community.md` is failing:

```
$ script/rss2html -n 4 --emails 'https://sympa.inria.fr/sympa/rss/latest_arc/caml-list?count=40'
Downloading https://sympa.inria.fr/sympa/rss/latest_arc/caml-list?count=40 ... done.
  (using cache /var/folders/qd/480pwlg91dg1ggqth6zxl1hm0000gn/T/ocamlorg-23e3896024b994f87ed7cf61447468fa, updated 0:02m30s ago).
Fatal error: exception Xmlm.Make(String)(Buffer).Error(_, -372779099)
Called from file "rss2html.ml", line 607, characters 14-40
Called from file "rss2html.ml", line 673, characters 34-70
```

@Chris00 Any idea how to fix this?

**Comment by amirmc** [comment]
I just tried rebuilding locally, following a `make clean` (which is what I should have tried earlier).  The community/index.html is now empty for me too, with the same error as above.

```
Downloading https://sympa.inria.fr/sympa/rss/latest_arc/caml-list?count=40 ... done.
  (using cache /var/folders/qd/hqj5q43509qbjgpgksjp99zm0000gp/T/ocamlorg-23e3896024b994f87ed7cf61447468fa, updated 0:18m17s ago).
Fatal error: exception Xmlm.Make(String)(Buffer).Error(_, -372779099)
Error: exception <Failure("Command <> ended with error <2>. Location: ocaml.org/community/index.fr.html.tmp:52:118.")>
```

**Comment by agarwal** [comment]
Yeah, and I can't find any occurrence of `Xmlm.Make` anywhere in the `ocaml.org` or `Syndic` repos. Not sure where this is coming from.

**Comment by amirmc** [comment]
I wonder that [this email](https://sympa.inria.fr/sympa/arc/caml-list/2015-09/msg00173.html) from the archive is triggering the problem.

The script above is being called from [here](https://github.com/ocaml/ocaml.org/blame/4377bed25578d120b9d0d47d075e1ad8895c12d4/site/community/index.md#L54) and [here](https://github.com/ocaml/ocaml.org/blame/4377bed25578d120b9d0d47d075e1ad8895c12d4/site/community/index.fr.md#L57).  Changing both those locations to have `?count=2` (instead of `?count=40`) means the site builds locally for me now. I presume that the number denotes the number of email messages to pull down in the feed. If it's 3 or higher, then it errors.

Putting the Xmlm error in google took me to [this page](http://discussions.citrix.com/topic/291684-failed-to-start-xapi-stuck-after-boot-via-iscsi/), where it mentions something about non-standard Ascii characters. 

Hopefully this is enough for someone else to go on.

**Comment by agarwal** [comment]
We just need two more messages to the mailing list for the problem to go away! Well I suppose a longer term fix to handle odd characters is needed.

**Comment by dbuenzli** [comment]
> Yeah, and I can't find any occurrence of Xmlm.Make anywhere in the ocaml.org or Syndic repos. Not sure where this is coming from.

There's an internal application to provide the API. A first good step would be to properly catch Xmlm exceptions an print them using Xmlm.error_message, there's no reason to be cryptic to the end users.

**Comment by amirmc** [comment]
> We just need two more messages to the mailing list for the problem to go away!

I think it needs to be 38 more messages, as that's what's pulled down by default (I'm guessing). :) From that, the threads are inferred and 4 are presented on the page. 

We can change the figure for the short term, just so the page is displayed again, but we should address the underlying problem too.

**Comment by agarwal** [comment]
My change in 5ccf9953925d8ee9882495f622004460288909ed was meant to be reverted, but I think it is okay to leave it. The rss2html script is being called with `-n 4`, which means we want to keep just 4 posts, and thus there's no reason to ask for more than that from the feed.

The general problem that some odd characters aren't handled isn't addressed still.

**Comment by agarwal** [comment]
We were again hit by this bug. The command `./script/rss2html -n 50 --aggregate ocaml.org/feed.xml` was again giving the same error as above. I believe this was due to an empty Caml Hump feed, which was leading to #852. I resolved by removing Caml Hump from our feeds list in c28f4bac46f1fe41c4bd82a7dcb9ef9358510479.

**Comment by Chris00** [comment]
The [new version of `Syndic`](https://github.com/ocaml/opam-repository/pull/7835) should not trigger the error.  I'll update it on the server when it is accepted.

**Comment by agarwal** [comment]
Thanks for the fix.
