### ISSUE TITLE
add OCaml Labs to Giving Support

### ISSUE THREAD

**Issue by agarwal** [ocaml/v2.ocaml.org#85]
Anil has been contacted for some text. Relevant logos can be taken from the bottom of [this page](http://www.cl.cam.ac.uk/projects/ocamllabs/people/index.html).

**Comment by amirmc** [comment]
@agarwal and @avsm, how about the following?

### Charitable Donations

You can also support OCaml via a charitible donation to [OCaml Labs](http://www.cl.cam.ac.uk/projects/ocamllabs), which is a project within the [Faculty of Computer Science](http://www.cl.cam.ac.uk) at the University of Cambridge.  Cambridge is a registered Charity and donations are often a tax-efficient and effective way to help expand your organisation's use of functional programming and ensure the long-term future of OCaml.

The goal of [OCaml Labs](http://www.cl.cam.ac.uk/projects/ocamllabs) is to push OCaml and functional programming forward as a platform, making it a more effective tool for current users (including significant industrial users) while at the same time growing the appeal of the language, broadening its applicability and popularity.  This will be achieved by a combination of technological advancements, creation of community infrastructure, and public communications. A core principle of OCaml Labs is that all the work will be freely released under open-source licenses, and efforts made to integrate work upstream (e.g to INRIA, who originally developed and have maintained OCaml since its release in 1996).

If you'd like to discuss making a donation, please [contact Anil Madhavapeddy](mailto:anil@recoil.org?subject=Donating to OCaml Labs) for more information.
