### ISSUE TITLE
Slack, Drift,...

### ISSUE THREAD

**Issue by Chris00** [ocaml/v2.ocaml.org#860]
A feature that has been requested a couple of times is to open a [Slack](https://slack.com/) forum.  In order not to split the community, @camelus should be used to build a bridge with IRC.

There are also other products that may be worth investigating such as [Drift](https://www.drift.com/) or even [Microsoft Teams](https://products.office.com/en-US/microsoft-teams/group-chat-software) if we think the later may be helping people working on Windows to join the community.

**Comment by dannywillems** [comment]
@Chris00 About Slack, there is OCaml Labs Slack. Do you think it's a solution?

There is also a Discord about Reason (https://discordapp.com/invite/reasonml) and a channel about OCaml is available.

**Comment by Chris00** [comment]
The problem is that people who do live chat are on IRC.  In order not to split the community a bridge is necessary — whatever additional channels are opened.

**Comment by mars0i** [comment]
As someone who's essentially new to OCaml who's spent a lot of time in the Clojure community in recent years, I want to suggest that it's a mistake to wait for an IRC bridge to be constructed.  Using Slack or gitter was discussed on the mailing list last summer, and this issue is from last winter.  In the mean time, anyone who's interested in OCaml and compares the community resources with what's available for F# (including a a Slack group and a real Google groups group) may think twice about pursuing OCaml rather than F#.  I would imagine that comparisons with Haskell or Scala would provide even more of a contrast.  (Clojure certainly has better community discussion resources than OCaml, but being dynamically typed, it's a different beast.)  So by waiting (for how long?) to build a bridge, I worry that OCaml is losing potential adopters.  Since program language adoption probably exhibits exponential effects, it's not good to miss out on what's going to be at least a year's worth of potential new users since last summer.   It's easy to create a Slack group.  Why not just do it?  Yes, it's better if there's a bridge.  Yes, you split resources if you don't have a bridge.  But some people will simply monitor both IRC and Slack until there's a bridge.  It's not that hard to do.  And others will simply use one or the other--IRC or Slack.  So what?  If the Slack group became at all popular, then I'd bet that most new users would gravitate to it rather than IRC.  That's OK. It's not that Slack is the be all and end all, but if there's no Slack group, and only a mailing list without a place like a Google group where you can post questions and announcements online, then the growth of the community is slowed.   (I also think that replacing the Yahoo newbie group with a Google group or some other technology would be worth considering.  I hate Yahoo groups because of the ads and functionality.  I just don't want to bother with a Yahoo group.  Too annoying.)

For the record, I personally have a strong default preference for OCaml over F# for several good reasons. The better community resources of F# is one reason that I continue look at F#.  I want OCaml to be successful, and I want to feel comfortable with the kind of support I'll have if I start using it at all seriously.  It's a great language.

**Comment by rgrinberg** [comment]
Yeah, I don't see how the community is split when more channels for communcation are open. Do we have a bridge between stackoverflow and the mailing lists for example? Do we need one?

> The problem is that people who do live chat are on IRC. In order not to split the community a bridge is necessary — whatever additional channels are opened.

I'm one of those people on IRC and I don't have a problem joining other avenues to talk about OCaml if they're of interest to me. I can't see why other IRC users should object to somebody discussing elsewhere.

**Comment by mars0i** [comment]
I guess someone might worry that there would be too little traffic in one or both of the forums.  If there aren't enough people talking, then there's no reason to visit.  A vicious cycle is possible.  My thought is that it's worth trying a Slack channel for a while, to see what happens.  

Perhaps that would make it more likely that someone would invest in constructing a bridge.

**Comment by agarwal** [comment]
@mars0i There is indeed no reason to wait. If you are motivated to do this, go for it. Then publicize it and hopefully people will join and it'll be useful.

**Comment by amirmc** [comment]
One of the issues with Slack specifically, is that there's a 10k message limit (on the free version) and you can hit that much quicker than you think.  Of course, this may not matter for the use-case you're thinking of, @mars0i.

I think it'd be worth having a look over other options before deciding.
- Reason seems to be doing well with [Discord](https://discordapp.com).
- Rust uses a combination of [Discourse](http://www.discourse.org) and StackOverflow.

I'm not suggesting this to put off any efforts at moving forward! I think the reality is that people will go with tools that they're familiar with and various projects already spread their discussions in a number of places.

**Comment by mars0i** [comment]
That all seems reasonable to me @amirmc.  I'm not familiar with those other platforms, and I have no particular investment in Slack other than that it seems to work for Clojure.  I don't know what impact the 10K limit has there; I've never tried to search very far back.  In any event I'm just an interested outsider to the OCaml community at this point, and all I can do is to offer some points to consider (and no significant time investment on my part).

**Comment by dannywillems** [comment]
I think something like Go community does with the Slack Gophers it's great. You can create for example a channel by Go projects.

**Comment by agarwal** [comment]
The community now has https://discuss.ocaml.org/. Does that resolve this issue?

**Comment by Chris00** [comment]
I think so but we may want to wait until July when [it will no longer be in beta](https://discuss.ocaml.org/t/discussion-site-status-and-timeline/23) before closing this issue.

**Comment by mars0i** [comment]
Before closing the issue, I think links to discuss.ocaml.org should be added to any pages on ocaml.org that direct people to mailing lists, help, etc.  These are the ones I know about:
http://ocaml.org/community/mailing_lists.html
http://ocaml.org/community/

Also, I think that one motivation for discuss.ocaml.org was to provide an alternative to the Yahoo beginner's group.  At least, it seems if as if the move was partly stimulated by my complaints about that group:
https://groups.google.com/forum/#!topic/ocaml-aggregation-list/P8jpwfFkvjQ
At some point in the future, the community may decide to encourage use of discuss.ocaml.org rather than the Yahoo group.  This might involve a few additional changes to the pages listed above.

**Comment by Chris00** [comment]
I have removed the mention of the Yahoo list and promoted the use of [discourse](https://discuss.ocaml.org/).
